# Generated by Django 3.1 on 2022-06-10 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0002_auto_20220610_1657'),
        ('users', '0002_auto_20210322_0640'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_description', models.TextField(max_length=500, null=True)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.AddConstraint(
            model_name='classroomfeed',
            constraint=models.CheckConstraint(check=models.Q(('assignment_id__isnull', False), ('feed_description__isnull', False), _connector='OR'), name='both_not_null'),
        ),
    ]
