# Generated by Django 3.1 on 2020-09-05 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=150)),
                ('assignment_description', models.CharField(max_length=500)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('classroom_id', models.ManyToManyField(to='classroom.Classroom')),
            ],
        ),
    ]
