# Generated by Django 3.1 on 2020-09-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_auto_20200904_0613'),
        ('users', '0001_initial'),
        ('assignment', '0002_auto_20200904_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=150)),
                ('assignment_description', models.CharField(max_length=500)),
                ('assignment_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('classroom_id', models.ManyToManyField(blank=True, to='classroom.Classroom')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
