# Generated by Django 3.0.8 on 2020-09-06 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200905_1057'),
        ('feed', '0004_auto_20200906_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomfeed',
            name='assignment_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment'),
        ),
    ]
