# Generated by Django 3.0.8 on 2020-09-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200905_1057'),
        ('feed', '0005_auto_20200906_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomfeed',
            name='classroom_id',
        ),
        migrations.AddField(
            model_name='classroomfeed',
            name='classroom_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
            preserve_default=False,
        ),
    ]
