# Generated by Django 3.0.8 on 2020-09-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomstudents',
            name='enrolled_student_id',
            field=models.ManyToManyField(blank=True, to='users.Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher'),
        ),
    ]
