# Generated by Django 3.1 on 2022-06-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210322_0640'),
        ('classroom', '0002_auto_20220623_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
