# Generated by Django 3.1 on 2022-06-10 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210322_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('paper', models.FileField(upload_to='assignment/')),
                ('points', models.IntegerField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentByStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_answer', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('assignment_link', models.URLField(blank=True, null=True)),
                ('submisson_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
