# Generated by Django 3.1 on 2022-07-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancevideomodel',
            name='user',
        ),
    ]
